### ISSUE TITLE
launch binder didn't work for me

### ISSUE THREAD

**Issue by pdwaggoner** [karthik/binder-test#3]
It said "taking longer than usual, hang tight", and was there for a while. For whatever its worth I wanted to share. Thanks for this repo!

**Comment by karthik** [comment]
Thank you! Unfortunately this type of error is beyond our control (it depends on the server load etc). Usually refreshing a few times, or clicking the binder badge a bit later will make it all work without any more tweaks. I'm discussing more with the binder team about this issue, but for now I'll close it. Really appreciate you giving this a go. 🙏
