### ISSUE TITLE
.Rproj.user folder and minimal gitignore

### ISSUE THREAD

**Issue by annakrystalli** [karthik/binder-test#4]
Transferring discussions in `holepuch` [#25](https://github.com/karthik/holepunch/issues/25) as they're actually related to `binder-test`:

Regarding funny things popping up into the workspace, it's definitely causing some unexpected behaviours for me.  For example, I just reran `write_compendium_description()` and now I also have an another file that oddly looks like it's modified:

![image](https://user-images.githubusercontent.com/5583057/60337901-34207100-999c-11e9-9bf3-976ea7f6f4a4.png)

![image](https://user-images.githubusercontent.com/5583057/60338030-a09b7000-999c-11e9-8401-9e7097b2cf8f.png)

DOH! I think I figured it out! It's actually an issue with `binder-test` repo. There's an `.Rproj.user/` in the template repo where it seems information that gets overwritten during use of the package is cached. Is this necessary for the tutorial?

Re: the `.Rhistory`, it's because the `.gitgnore` in the `binder-test` repo is super minimal and doesn't seem to contain some defaults in an RStudio project `.gitignore` which I guess I've just come to expect to, ie:

```
.Rproj.user
.Rhistory
.RData
.Ruserdata
```

**Comment by karthik** [comment]
Awesome, thanks for catching this. :) 
Fixed.
