### ISSUE TITLE
Build time normal? 

### ISSUE THREAD

**Issue by nilescbn** [karthik/binder-test#5]
Thank you for creating this. I've been wanting to try Binder for awhile and `holepunch` makes it a lot more accessible to me.

Without ever having committed or pushed anything to GitHub before, I was able to get your binder-test example working [here](https://github.com/nilescbn/binder_test). The instructions were great (as some minor feedback, I did fumble around a bit with the commit and push steps, so maybe a link to some basic advice for folks there would be helpful).

I filed this issue because the build took a lot longer than I was anticipating. Yesterday it took ~25 minutes. After that initial build, the image only took a minute or two to load after launching afresh from the "launch binder" badge. 

However, I tried again today and the Build took even longer.  At around the 30 minute mark, I started paying closer attention to the Build log. Packages were being installed from MRAN. A few minutes later, the process seemed to get hung up and I got a failed connection message (which I failed to capture). The build process seemed to freeze after that. Seeing that, I refreshed the browser and the RStudio screen launched within 30 seconds or so. 

So my question: is that build time to be expected/normal? Or might I be doing something wrong? If the former, I can understand why. Watching the Build logs, there are a lot of installations happening. I see your mentions of server loads too in answers to earlier issues. 

I'm wondering about the latter because your [holepunch README](https://github.com/karthik/holepunch#alternate-setup-method)  mentiones that the Alternate setup method *"will take a very long time."* I did follow the code on the [binder-test README](https://github.com/karthik/binder-test), so I figured I was following your compendium setup. Yet I also saw mention in [this issue](https://github.com/karthik/binder-test/issues/1) of the inital image taking "30 seconds to several minutes" to create.  So I was, again, thinking that 25 minutes to more than 30 minutes was longer than typical. 

In sum, thank you again for making this available. Any tips or assurances that the build times I've been experiencing are what to to expect would be appreciated. Please let me know if additional information from me would be helpful.

**Comment by karthik** [comment]
Thank you for this feedback! 🙏

> I did fumble around a bit with the commit and push steps, so maybe a link to some basic advice for folks there would be helpful

Will do.

> However, I tried again today and the Build took even longer. At around the 30 minute mark, I started paying closer attention to the Build log. Packages were being installed from MRAN. A few minutes later, the process seemed to get hung up and I got a failed connection message (which I failed to capture). The build process seemed to freeze after that. Seeing that, I refreshed the browser and the RStudio screen launched within 30 seconds or so.

Build times are generally variable depending on server load, complexity of your setup, how many packages you're installing and how much is already in a Docker image. But 30 minutes for this example is way too long. You can always refresh and see what happens. Without seeing the exact error message, it's possible that MRAN may have been slow or down or timed out at that very moment. One way to start a new build is to make another commit (however trivial. You could edit a bit of text in the README for example). Then push and run `build_binder()` and it will start a new build. 

> I'm wondering about the latter because your holepunch README mentiones that the Alternate setup method "will take a very long time." I did follow the code on the binder-test README, so I figured I was following your compendium setup.

Correct. Without the approach I have outlined here (a description file + a Dockerfile that relies on an image that contains most of the core tools), using parts of the tidyverse (say `dplyr`) will take several hours to build from source. I once waited 4 hours before everything timed out. 

> So I was, again, thinking that 25 minutes to more than 30 minutes was longer than typical.

Right, so this seems off for some reason. If it happens again please let me know and I'll investigate further. You can also check the [binder dashboard](https://grafana.mybinder.org/d/3SpLQinmk/1-overview?refresh=1m&orgId=1) to see if they are having an off day.

> In sum, thank you again for making this available. Any tips or assurances that the build times I've been experiencing are what to to expect would be appreciated. Please let me know if additional information from me would be helpful.

Thanks again for this detailed feedback. I really appreciate it. I'll expand the vignette to write more on speeding up load times. In a nutshell, the more you can capture in your own Docker image, the faster you can make this go. I'll update this thread when I am able to write that up in detail. 

Cheers.
